[xpCost]
inverseXpCost = false
blocksPerXpLevel = 1000
minimumBaseXpCost = 0.0
maximumBaseXpCost = 0.0
xpCostPerLeashed = 0
dimensionalWarpXpCost = 0
globalWaystoneXpCostMultiplier = 0.0
warpStoneXpCostMultiplier = 0.0
waystoneXpCostMultiplier = 0.0
sharestoneXpCostMultiplier = 1.0
portstoneXpCostMultiplier = 0.0
warpPlateXpCostMultiplier = 0.0
inventoryButtonXpCostMultiplier = 0.0
[restrictions]
restrictToCreative = false
restrictRenameToOwner = false
generatedWaystonesUnbreakable = false
transportLeashed = true
transportLeashedDimensional = true
leashedDenyList = ["minecraft:wither"]
dimensionalWarp = "ALLOW"
dimensionalWarpAllowList = []
dimensionalWarpDenyList = []
allowWaystoneToWaystoneTeleport = true
globalWaystoneSetupRequiresCreativeMode = true
[cooldowns]
globalWaystoneCooldownMultiplier = 0.0
warpStoneCooldown = 0
warpStoneUseTime = 0
warpPlateUseTime = 0
scrollUseTime = 0
inventoryButtonCooldown = 0
[inventoryButton]
inventoryButton = ""
warpButtonX = 58
warpButtonY = 60
creativeWarpButtonX = 88
creativeWarpButtonY = 33
[worldGen]
worldGenStyle = "BIOME"
frequency = 25
dimensionAllowList = ["minecraft:overworld", "minecraft:the_nether", "minecraft:the_end"]
dimensionDenyList = []
nameGenerationMode = "PRESET_FIRST"
customWaystoneNames = []
spawnInVillages = true
forceSpawnInVillages = true
[client]
disableTextGlow = false
disableParticles = false
[compatibility]
displayWaystonesOnJourneyMap = true
preferJourneyMapIntegration = true
