debug = false
disable_crowdin = false
check_for_updates = false

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.whisper.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 340
type = "KEYSYM"

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 0.8
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = true
activation_threshold = -60.0
input_device = ""
output_device = ""
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = true
hrtf = true
stereo_capture = false

[voice.volumes.proximity]
volume = 1.0
[voice.volumes.whisper]
volume = 0.5

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = false
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
whisper = "OFF"
